vocatwk/CodeU-Nemo

- src/main/webapp/WEB-INF/appengine-web.xml
- src/main/webapp/about.jsp
#Added my bio and merging I think
> Jasmine chau

- src/main/webapp/WEB-INF/appengine-web.xml
- src/main/webapp/about.jsp
- src/main/webapp/index.jsp
Edited homepage and included our project ID to publish our app. Also added an about me section.
> Published app and added about me

- src/main/java/codeu/controller/ProfileServlet.java
- src/main/java/codeu/model/store/basic/MessageStore.java
- src/main/webapp/WEB-INF/view/chat.jsp
- src/main/webapp/WEB-INF/view/conversations.jsp
- src/main/webapp/WEB-INF/view/login.jsp
- src/main/webapp/WEB-INF/view/profile.jsp
- src/main/webapp/WEB-INF/view/register.jsp
- src/main/webapp/WEB-INF/web.xml
- src/main/webapp/about.jsp
- src/main/webapp/index.jsp
Most of the new code is in ProfileServlet.java. I have implemented only things I need to get the doGet() method working and I have a method header for the doPost(). I have added this servlet class and its corresponding url pattern in web.xml. I have also added a profile.jsp file that has the same nav bar as the other pages but with an additional message. (I've attached a screenshot below). I have also edited all jsp files(just the nav bars to include a link to the profile of the user logged in.) I've also added a method in MessageStore.java that lets me access messages in any conversation from a specific author(this is really for functions I have yet to implement so it's not used for prototype)
> Added prototype for profile pages

- src/main/java/codeu/controller/ActivityFeedServlet.java
- src/main/webapp/WEB-INF/view/activityfeed.jsp
- src/main/webapp/WEB-INF/web.xml
I created the activity feed servlet and it's corresponding jsp file. I also updated web.xml to map to the corresponding url. Currently, the activity feed page doesn't fetch any data and only has the doGet() method implemented. Here's a screenshot:
> Added Prototype for Activity Feed

- src/test/java/codeu/controller/ActivityFeedServletTest.java
Test for the doGet() function from the ActivityFeedServlet class. Will test doPost() once it is implemented.
> Test for ActivityFeedServlet doGet()

- src/main/java/codeu/controller/ProfileServlet.java
- src/main/java/codeu/model/store/basic/MessageStore.java
- src/main/webapp/WEB-INF/view/chat.jsp
- src/main/webapp/WEB-INF/view/profile.jsp
I have fixed the implementation of the prototype for profile pages according to comments on previous PR and the bug that Guillermo found.
> Fixes to Profile page prototype

- src/main/java/codeu/controller/ActivityFeedServlet.java
- src/main/webapp/WEB-INF/view/activityfeed.jsp
I removed unnecessary imports and turned tabs into spaces.
> Fixed Activity Feed Imports and Spacing

- src/test/java/codeu/controller/ProfileServletTest.java
I added 3 tests: doGet() with a bad url, navigating to a profile of a non-existent user, and with correct url + mock user.
> Added tests for Profile pages prototype

- src/main/java/codeu/controller/ProfileServlet.java
- src/main/java/codeu/model/data/User.java
- src/main/java/codeu/model/store/persistence/PersistentDataStore.java
- src/main/webapp/WEB-INF/view/profile.jsp
- src/main/webapp/css/main.css
Each profile page is now able to display users' sent messages and About Me sections(as well giving users the ability to edit it). I have attached screenshots below. The second one is when the user is logged in and looking at their own profile. The first is when the user isn't either of those things. I had to edit User.java to allow storing and editing AboutMe messages and persistentDataStore.java in order to store and retrieve aboutMe messages from DataStore. I've also added a style for the messages in main.css.
> Added Profile pages MVP

- src/main/java/codeu/controller/ActivityFeedServlet.java
- src/main/webapp/WEB-INF/view/activityfeed.jsp
I integrated the conversations into the activity feed. I also combined events by using a sorted map so that I could easily sort the events chronologically by their creation time. I'll add the messages and update the tests later on.
Here's a screenshot:
> Fetched conversations for activity feed

- src/main/java/codeu/controller/ActivityFeedServlet.java
- src/main/java/codeu/model/store/basic/MessageStore.java
- src/main/webapp/WEB-INF/view/activityfeed.jsp
- src/main/webapp/css/main.css
- src/test/java/codeu/controller/ActivityFeedServletTest.java
All users, conversations, and messages are now displayed in the activity feed. I added a function to access all of the messages which ideally will be removed once I make an Event class. I also removed the unnecessary unsorted map I had before. Also, I updated the CSS for this page. I still have to implement this using the Store classes so that I could access a user by their ID (same for other classes).
Here's a screenshot:
> Activity Feed MVP

- src/main/webapp/WEB-INF/view/activityfeed.jsp
- src/main/webapp/WEB-INF/view/chat.jsp
- src/main/webapp/WEB-INF/view/conversations.jsp
- src/main/webapp/WEB-INF/view/login.jsp
- src/main/webapp/WEB-INF/view/navbar.jsp
- src/main/webapp/WEB-INF/view/profile.jsp
- src/main/webapp/WEB-INF/view/register.jsp
- src/main/webapp/about.jsp
- src/main/webapp/index.jsp
Implemented changes based on recent issue. The code for the navigation bar is now in navbar.jsp and this file is included in all other jsp files where the previous code used to be. Also added tab for activity feed.
Here's a screenshot:
> Implemented Navigation Bar Changes

- src/main/java/codeu/controller/ActivityFeedServlet.java
- src/main/java/codeu/model/data/Event.java
- src/main/java/codeu/model/store/basic/ConversationStore.java
- src/main/java/codeu/model/store/basic/MessageStore.java
- src/main/webapp/WEB-INF/view/activityfeed.jsp
- src/main/webapp/WEB-INF/view/chat.jsp
- src/main/webapp/WEB-INF/view/conversations.jsp
- src/main/webapp/WEB-INF/view/login.jsp
- src/main/webapp/WEB-INF/view/navbar.jsp
- src/main/webapp/WEB-INF/view/profile.jsp
- src/main/webapp/WEB-INF/view/register.jsp
- src/main/webapp/about.jsp
- src/main/webapp/index.jsp
I implemented an Event class to be used for the Activity Feed. I then added getConversation() with a given Id in ConversationStore.
Also, this is my first time making a PR from another branch so let me know if there are any problems. Just wondering if I did this correctly:
```git checkout -b NewBranch```
```git pull origin OldBranch```
```git push origin NewBranch```
> Implemented Event Class

- src/main/java/codeu/controller/ProfileServlet.java
- src/test/java/codeu/controller/ProfileServletTest.java
I added 3 tests: where user is logged in and navigating to other users' profiles and their own profile, and one where user is not logged in.
> Added tests for profile pages MVP

- src/main/java/codeu/controller/ActivityFeedServlet.java
- src/main/java/codeu/controller/ChatServlet.java
- src/main/java/codeu/controller/ConversationServlet.java
- src/main/java/codeu/controller/ProfileServlet.java
- src/main/java/codeu/controller/RegisterServlet.java
- src/main/java/codeu/controller/ServerStartupListener.java
- src/main/java/codeu/model/store/basic/EventStore.java
- src/main/webapp/WEB-INF/view/activityfeed.jsp
I updated the appropriate servlets that stored information to the datastore by storing to the EventStore. Then I updated how the Activity Feed page is rendered. To see these changes locally, you'll have to run the clean command.
I will work on updating the tests.
> Updated Activity Feed with the Event Class Implementation

- src/main/java/codeu/controller/ChatServlet.java
- src/main/java/codeu/model/data/Conversation.java
- src/main/java/codeu/model/store/basic/ConversationStore.java
- src/main/java/codeu/model/store/persistence/PersistentDataStore.java
- src/main/webapp/WEB-INF/view/chat.jsp
- src/test/java/codeu/controller/ChatServletTest.java
I have added a settings button next to the conversation title in the chat page(I haven't paid attention to css yet) that shows an option to make the conversation private when you click it. When users click this button, the conversation, if not already private, becomes private. Nothing happens otherwise.
I have also added 2 test for the extra code in the doPost method of ChatServlet, to test the conditions in which the user is trying to make a public or an already private conversation method, private.
resolves #42
> Added an option to let users make conversations private

- .travis.yml
Added the `.travis.yml` file.
"Fixes #47 "
> Set Up Travis

- src/main/java/codeu/controller/AdminServlet.java
- src/main/java/codeu/controller/RegisterServlet.java
- src/main/java/codeu/model/data/User.java
- src/main/java/codeu/model/store/basic/ConversationStore.java
- src/main/java/codeu/model/store/basic/MessageStore.java
- src/main/java/codeu/model/store/basic/UserStore.java
- src/main/java/codeu/model/store/persistence/PersistentDataStore.java
- src/main/webapp/WEB-INF/view/admin.jsp
- src/main/webapp/WEB-INF/view/conversations.jsp
- src/main/webapp/WEB-INF/view/navbar.jsp
- src/main/webapp/WEB-INF/view/profile.jsp
- src/main/webapp/WEB-INF/view/register.jsp
- src/main/webapp/WEB-INF/web.xml
- src/test/java/codeu/controller/AdminServletTest.java
- src/test/java/codeu/model/store/persistence/PersistentDataStoreTest.java
I am sorry I am so late on this. This should be working I still need a way to implement who is the admin, I was thinking of a button that sends a request to current admins to approve if the user can become an admin. But you won't be able to access the page locally without being an admin. I was also wondering if there was a way to but an admin tab on the navigation bar only if the user is an admin.
> Working MVP Admin Page

- src/main/java/codeu/controller/SearchServlet.java
- src/main/java/codeu/model/store/basic/MessageStore.java
- src/main/java/codeu/model/store/basic/UserStore.java
- src/main/webapp/WEB-INF/view/navbar.jsp
- src/main/webapp/WEB-INF/view/search.jsp
- src/main/webapp/WEB-INF/view/searchbar.jsp
- src/main/webapp/WEB-INF/web.xml
- src/main/webapp/css/main.css
Added a search bar to the navigation bar. Empty searches are disabled. Currently only searching for users and getting/displaying them as a list. Will add tests in another PR.
Search Bar:
Empty Search:
Valid Search:
> Added a search bar, only searching Users for now

- README.md
I've added changes I can think of to our README.md. This isn't really worthy of a pull request but I didn't want to make a change to README directly just incase you guys wanted to change things or this isn't what you had in mind.
> Added changes I've made to README.md

- src/main/webapp/WEB-INF/view/navbar.jsp
I made a typo when I was fixing a merge conflict and merged it afterwards. Sorry about that.
> Fixed Typo in NavBar

- src/main/java/codeu/controller/NotificationServlet.java
- src/main/java/codeu/model/data/User.java
- src/main/java/codeu/model/store/basic/EventStore.java
- src/main/webapp/WEB-INF/view/navbar.jsp
- src/main/webapp/WEB-INF/view/notifications.jsp
- src/main/webapp/WEB-INF/view/searchbar.jsp
This is what I thought coded to generate a list of events that happen after the user Instant "lastSeenNotificationsTimestamp"
> Displaying the notifications to the user.

- src/test/java/codeu/controller/SearchServletTest.java
- src/test/java/codeu/model/store/basic/UserStoreTest.java
Added tests for the search bar. 
Fixes #58
> Search Bar Tests

- src/main/java/codeu/controller/BotController.java
- src/main/java/codeu/controller/ChatServlet.java
- src/main/java/codeu/model/data/Bot.java
- src/main/java/codeu/model/data/NemoBot.java
I made a `Bot` interface, which is very simple. Perhaps more stuff can be added later on. The former `Bot` class was renamed to `NemoBot`. Most of the new work is in `BotController`. I wanted to send this PR to get feedback before updating `ChatServlet`. The same goes for tests - I'll add them in a future PR once the initial framework changes are complete. 
EDIT: I semi-updated `ChatServlet` to work around the name changes. The changes don't reflect the addition of `BotController`.
Resolves #88
> Bot Framework

- src/main/java/codeu/controller/RegisterServlet.java
- src/test/java/codeu/controller/RegisterServletTest.java
Added a check for password length. A minimum of 6 characters is required. Also, do we want to disable spaces on passwords? 
Closes #92
> Password length check

- src/main/java/codeu/controller/ServerStartupListener.java
Moved `BotController` declaration into try-catch block. This seemed to stop giving me the error mentioned in the chat.
> Fixed deployment problem

- src/main/java/codeu/model/store/persistence/PersistentDataStore.java
- src/main/webapp/WEB-INF/view/chat.jsp
- src/test/java/codeu/controller/ChatServletTest.java
There was a PersistentDataStoreException and a NullReferenceException caused by the lastSeenNotification field on nemobot that I added some null checks for.
> Fixes errors in master branch

- src/main/webapp/WEB-INF/view/addUserBox.jsp
- src/main/webapp/WEB-INF/view/chat.jsp
- src/main/webapp/css/main.css
Fixes for the add user dialog:
> CSS touches

- src/main/webapp/WEB-INF/view/activityfeed.jsp
- src/main/webapp/WEB-INF/view/profile.jsp
These pages now show/hide conversation events and messages depending on their privacy status.
> Activity Feed and Profiles Handle Privacy Settings

- src/main/java/codeu/controller/ChatServlet.java
- src/main/java/codeu/model/data/Conversation.java
- src/main/java/codeu/model/data/User.java
- src/main/java/codeu/model/store/basic/MessageStore.java
- src/main/java/codeu/model/store/persistence/PersistentDataStore.java
- src/main/webapp/WEB-INF/view/chat.jsp
- src/main/webapp/WEB-INF/view/conversations.jsp
- src/main/webapp/WEB-INF/view/navbar.jsp
- src/main/webapp/css/main.css
- src/main/webapp/index.jsp
- src/test/java/codeu/controller/ChatServletTest.java
I updated the UI for conversations page.
I really wanted to implement those icons with the number of messages not yet seen next to each conversation like those in @yebrahim's design cause they just look really cool to have. But I'm not sure if it's that important since the user will see those messages were sent in his notifications page. But I still think it would be a cool feature to have. Let me know what you guys think.
Also while I was thinking of the above, I realized we'd have to account for messages coming in while the user is in the chat. Right now, it won't be difficult to implement because we only update messages in the chat on page reload but that got me thinking that getting those messages without having to refresh might also be good to have. It could be very inefficient at …
> Updated UI for conversations and chat page

- src/main/webapp/WEB-INF/view/activityfeed.jsp
- src/main/webapp/WEB-INF/view/navbar.jsp
- src/main/webapp/css/main.css
New look for the Activity Feed. Let me know if you think any more styling is needed.
> Activity Feed UI

- src/main/java/codeu/controller/ActivityFeedServlet.java
- src/main/java/codeu/controller/BotController.java
- src/main/java/codeu/controller/BotServlet.java
- src/main/java/codeu/model/data/Bot.java
- src/main/java/codeu/model/data/ConversationStatBot.java
- src/main/java/codeu/model/data/NemoBot.java
- src/main/webapp/WEB-INF/view/bots.jsp
- src/main/webapp/WEB-INF/view/navbar.jsp
- src/main/webapp/WEB-INF/web.xml
- src/main/webapp/css/main.css
- src/test/java/codeu/controller/BotServletTest.java
- src/test/java/codeu/model/data/ConversationStatBotTest.java
- src/test/java/codeu/model/data/NemoBotTest.java
Based on the feedback we got some people recommended a page with information about the bots we offer so here it is.
> Made a page for Bots

- src/main/webapp/WEB-INF/view/chat.jsp
- src/main/webapp/css/main.css
I fixed the id selector on `scrollChat()` and added `word-break: break-word` to handle long messages.
> Small Changes in Chat Display

- src/main/webapp/WEB-INF/view/navbar.jsp
- src/main/webapp/WEB-INF/view/notifications.jsp
- src/main/webapp/css/main.css
if anyone has suggestions I am open to them
> Notification ui

- src/main/java/codeu/controller/RegisterServlet.java
- src/test/java/codeu/controller/RegisterServletTest.java
I was able to register with an empty username which disabled all links to that profile, so I added this check.
> 1 Letter or Number for Username

- src/main/webapp/WEB-INF/view/navbar.jsp
- src/main/webapp/css/main.css
The navbar now collapses on smaller screen sizes. 
However, I ran into a problem with the search bar results. When the first result is clicked, it triggers the dropdown menu instead.
> Navbar collapses

- src/main/webapp/WEB-INF/view/activityfeed.jsp
- src/main/webapp/WEB-INF/view/profile.jsp
- src/main/webapp/css/main.css
The profile messages only show if the conversation is public and both the owner of the profile and the user logged in are part of the conversation.
> Profile UI
